name: cat_trivia
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.9

  #Internationalization
  intl: ^0.18.0

  #Injector
  get_it: ^7.2.0

  #Bloc
  flutter_bloc: ^7.1.0

  #Freezed
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0

  #Api
  retrofit: ^3.0.1
  dio: ^4.0.0-prev3
  pretty_dio_logger: ^1.2.0-beta-1

  #Serializable
  json_serializable: ^6.1.4
  json_annotation: ^4.7.0

  #Cache
  shared_preferences: ^2.0.15
  drift: ^2.3.0
  sqlite3_flutter_libs: ^0.5.0

  #Shimmer
  shimmer: ^2.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: ^5.2.0
  build_runner: ^2.0.1
  analyzer: ^5.2.0
  drift_dev: ^2.3.3
  retrofit_generator: ^4.0.0

flutter:
  uses-material-design: true
